services:

  restore:
    image: busybox
    volumes:
      - db-data:/data
      - ./db-data.tar.gz:/backup/db-data.tar.gz
    entrypoint: >
      sh -c "
        if [ ! -f /data/mongod.lock ]; then
          tar xzf /backup/db-data.tar.gz -C /data;
        fi"
    restart: "no"

  mongodb:
    image: mongo:8.0
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - db-data:/data/db

  server:
    build:
      context: .
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - mongodb

  
      
volumes:
  db-data:


